# Generated by Django 3.2.4 on 2022-01-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='orders',
            field=models.ManyToManyField(to='foodDelivery.Order'),
        ),
    ]
