# Generated by Django 3.2.4 on 2022-01-11 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_fooditem_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='orders',
        ),
    ]
