# Generated by Django 3.2.4 on 2022-01-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0004_fooditem_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='orders',
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodDelivery.fooditem'),
        ),
        migrations.AlterField(
            model_name='orderfooditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='foodDelivery.order'),
        ),
    ]
