# Generated by Django 3.2.4 on 2022-01-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0007_auto_20220111_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(to='foodDelivery.FoodItem'),
        ),
    ]
