# Generated by Django 3.2.4 on 2022-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0008_order_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='orders',
            field=models.ManyToManyField(related_name='food_items', through='foodDelivery.OrderFoodItem', to='foodDelivery.Order'),
        ),
    ]
