# Generated by Django 2.1.5 on 2022-01-09 20:04

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[twitter.models.validate_age]),
        ),
    ]
