# Generated by Django 2.1.5 on 2022-01-09 20:10

from django.db import migrations, models
import twitter.models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20220109_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(max_length=4, validators=[twitter.models.validate_account]),
        ),
    ]
